from PyQt5 import QtCore, QtGui, QtWidgets
import os
import sys
import subprocess
import plow_rc


def updateclient():
    os.system('echo "Lets get Spare updated for you." ; cd ~/spare-blockchain ; . ./activate ; spare stop all ; deactivate ; sudo kill -9 $(sudo lsof -t -i:55500,58448,58449,58447,58444) ; cd ~/ ; mkdir ~/plow ; mkdir ~/plow/old-config ; rm -f --recursive -d ~/plow/old-config/.spare-blockchain ; echo "Saving Mainnet folder in ~plow/old-config" ; mv ~/.spare-blockchain -t ~/plow/old-config/ ; rm -f --recursive -d ~/spare-blockchain ; git clone https://github.com/Spare-Network/spare-blockchain.git ; cd ~/spare-blockchain ; sh install.sh ; . ./activate ; spare init ; cd ~/plow/old-config/.spare-blockchain/mainnet ; mv db wallet -t ~/.spare-blockchain/mainnet ; cd ~/spare-blockchain ; spare start farmer ; echo "Spare has been Updated! The old Mainnet folder is saved in ~/plow/old-config, Add Your Plot Directories!" ; xdg-open ~/.spare-blockchain/mainnet/config/config.yaml ; xdg-open ~/plow/plot-directories.yaml')
    
def installcli():
    os.system('echo "Lets get Spare installed for you." ; cd ~/ ; sudo kill -9 $(sudo lsof -t -i:55500,58448,58449,58447,58444) ; git clone https://github.com/Spare-Network/spare-blockchain.git ; cd ~/spare-blockchain ; sh install.sh ; . ./activate ; spare init ; cd ~/plow/old-config/.spare-blockchain/mainnet ; mv db wallet -t ~/.spare-blockchain/mainnet ; cd ~/spare-blockchain ; spare keys add ; spare start farmer ; echo "Spare has been installed, Add Your Plot Directories!!" ; xdg-open ~/.spare-blockchain/mainnet/config/config.yaml ; xdg-open ~/plow/plot-directories.yaml')
    
#uninstall
def uninstallclient():
    os.system('echo "Lets get Spare uninstalled for you." ; cd ~/spare-blockchain ; . ./activate ; spare stop all ; deactivate ; cd ~/ ; mkdir ~/plow ; mkdir ~/plow/old-config ; rm -f --recursive -d ~/plow/old-config/.spare-blockchain ; mv ~/.spare-blockchain -t ~/plow/old-config/ ; rm -f --recursive -d ~/spare-blockchain ; echo "Spare has been Uninstalled. Old Mainnet folder is saved in ~/plow/old-config"')
    
def deleteclient():
    os.system('echo "Lets get Spare deleted for you." ; cd ~/ ; mkdir ~/plow ; mkdir ~/plow/old-config ; rm -f --recursive -d ~/plow/old-config/.spare-blockchain ; mv ~/.spare-blockchain -t ~/plow/old-config/ ; rm -f --recursive -d ~/spare-blockchain ; echo "Spare has been Deleted. The old Mainnet folder has been saved in ~/plow/old-config"') 

def keysshow():
    os.system('echo "Getting Spare Fingerprint, Pool & Farmer Public Plot Keys..." ; cd ~/spare-blockchain ; . ./activate ; spare keys show')
    
def mnemonic():
    os.system('echo "Getting Active Spare Mnemonic Key..." ; cd ~/spare-blockchain ; . ./activate ; spare keys show --show-mnemonic-seed')
	
def genandprintkey():
    os.system('echo "Generating and Printing New Spare Mnemonic Key..." ; cd ~/spare-blockchain ; . ./activate ; spare generate_and_print')

def addkey():
    os.system('echo "Please Wait For Prompt To Add Existing Spare Keys..." ; cd ~/spare-blockchain ; . ./activate ; spare keys add')
	
def genkey():
    os.system('echo "Generating New Spare Mnemonic key..." ; cd ~/spare-blockchain ; . ./activate ; spare keys generate')

def stop():
    os.system('echo "Stopping Spare..." ; cd ~/spare-blockchain ; . ./activate ; spare stop all')
	
def version():
    os.system('echo "Spare Verion Number..." ; cd ~/spare-blockchain ; . ./activate ; spare version')

def startcli():
    os.system('echo "Starting Spare..." ; cd ~/spare-blockchain ; . ./activate ; spare stop all ; deactivate ; cd ~/ ; cd ~/spare-blockchain ; . ./activate ; spare start farmer')

def chain():
    os.system('echo "Getting The State Of Spare Blockchain..." ; cd ~/spare-blockchain ; . ./activate ; spare show -s')

def connections():
    os.system('echo "Getting Spare Peer Connections..." ; cd ~/spare-blockchain ; . ./activate ; spare show -c')

def wallet():
    os.system('echo "Spare Wallet Is Loading..." ; cd ~/spare-blockchain ; . ./activate ; spare wallet show')

def getaddress():
    os.system('echo "Getting Spare Address..." ; cd ~/spare-blockchain ; . ./activate ; spare wallet get_address')

def gettransactions():
    os.system('echo "Getting Spare Transactions..." ; cd ~/spare-blockchain ; . ./activate ; spare wallet get_transactions')
	
def summary():
    os.system('echo "Spare Farm Summary Loading..." ; cd ~/spare-blockchain ; . ./activate ; spare farm summary')
	
def challenges():
    os.system('echo "Spare Challenges Loading..." ; cd ~/spare-blockchain ; . ./activate ; spare farm challenges ; echo "End Of Challenges"')
    
def config():
    os.system('echo "Opening Spare Config File..." ; xdg-open ~/.spare-blockchain/mainnet/config/config.yaml')
    
def log():
    os.system('echo "Opening Spare Log File..." ; xdg-open ~/.spare-blockchain/mainnet/log/debug.log')
    
def startgui():
    os.system('echo "Starting Spare-GUI..." ; cd ~/spare-blockchain ; . ./activate ; cd spare-blockchian-gui ; npm run electron')  
    
def installgui():
    os.system('echo "Lets get Spare-GUI installed for you." ; cd ~/spare-blockchain ; . ./activate ; sh install-gui.sh ; cd spare-blockchian-gui ; npm run electron')
  
def closedaemonport():
    os.system('echo "Closing Spare Daemon Port..." ; sudo kill -9 $(sudo lsof -t -i:55500) ; echo "Process IDs On Daemon Port 55500 Closed"')             

def closefarmerport():
    os.system('echo "Closing Spare Farmer Port..." ; sudo kill -9 $(sudo lsof -t -i:58447) ; echo "Process IDs On Farmer Port 58447 Closed"')

def closeharvesterport():
    os.system('echo "Closing Spare Harvester Port..." ; sudo kill -9 $(sudo lsof -t -i:58448) ; echo "Process IDs On Harvester Port 58448 Closed"')

def closefullnodeport():
    os.system('echo "Closing Spare Full-Node Port..." ; sudo kill -9 $(sudo lsof -t -i:58444) ; echo "Process IDs On Full Node Port 58444 Closed"')

def closewalletport():
    os.system('echo "Closing Spare Wallet Port..." ; sudo kill -9 $(sudo lsof -t -i:58449) ; echo "Process IDs on Wallet Port 58449 Closed"')

def listports():
    os.system('echo "List of All Spare Process IDs for Ports, Daemon 55500, Harvester 58448, Wallet 58449, Farmer 58447, Full Node 58444." ; echo "For more details on Active Process IDs, use Extras Tab on Main Window." ; sudo lsof -t -i:55500,58448,58449,58447,58444')

def closeallport():
    os.system('echo "Closing All Spare Ports..." ; sudo kill -9 $(sudo lsof -t -i:55500,58448,58449,58447,58444) ; echo "All Process IDs on Ports, Daemon 55500, Harvester 58448, Wallet 58449, Farmer 58447, Full Node 58444, are closed"')

def terminal():
    subprocess.call('echo "Opening Terminal in Spare Folder" ; cd ~/spare-blockchain ; x-terminal-emulator -- ', shell =True)


class Ui_SpareWindow(object):
    def setupUi(self, SpareWindow):
        SpareWindow.setObjectName("SpareWindow")
        SpareWindow.resize(483, 320)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(28, 113, 216))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(102, 171, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(65, 142, 235))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(14, 57, 108))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(19, 75, 144))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(7, 69, 88))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(141, 184, 235))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(28, 113, 216))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(102, 171, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(65, 142, 235))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(14, 57, 108))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(19, 75, 144))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(7, 69, 88))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(141, 184, 235))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(14, 57, 108))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(28, 113, 216))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(102, 171, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(65, 142, 235))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(14, 57, 108))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(19, 75, 144))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(14, 57, 108))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(14, 57, 108))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(7, 69, 88))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(7, 69, 88))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(28, 113, 216))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
#START MAIN WINDOW
        SpareWindow.setPalette(palette)
#ICON
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/theme/plow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        SpareWindow.setWindowIcon(icon)
#MAIN WINDOWS SPECS
        self.centralwidget = QtWidgets.QWidget(SpareWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayoutmain = QtWidgets.QGridLayout()
        self.gridLayoutmain.setSpacing(0)
        self.gridLayoutmain.setObjectName("gridLayoutmain")
        self.MainTab = QtWidgets.QTabWidget(self.centralwidget)
        self.MainTab.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MainTab.sizePolicy().hasHeightForWidth())
        self.MainTab.setSizePolicy(sizePolicy)
#END MAIN WINDOW SPECS
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(25, 186, 227))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(113, 226, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(69, 206, 241))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(12, 93, 113))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(17, 124, 151))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(119, 118, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(140, 220, 241))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(25, 186, 227))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(113, 226, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(69, 206, 241))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(12, 93, 113))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(17, 124, 151))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(119, 118, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(140, 220, 241))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(12, 93, 113))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(25, 186, 227))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(113, 226, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(69, 206, 241))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(12, 93, 113))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(17, 124, 151))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(12, 93, 113))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(12, 93, 113))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(25, 186, 227))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.MainTab.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Fira Sans")
        font.setBold(True)
        font.setWeight(75)
        self.MainTab.setFont(font)
        self.MainTab.setMouseTracking(True)
        self.MainTab.setTabletTracking(True)
        self.MainTab.setAutoFillBackground(True)
        self.MainTab.setStyleSheet("")
        self.MainTab.setObjectName("MainTab")
#START DASHBOARD TAB
        self.dashboardtab = QtWidgets.QWidget()
        self.dashboardtab.setObjectName("dashboardtab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.dashboardtab)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
#connections
        self.connections = QtWidgets.QPushButton(self.dashboardtab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.connections.sizePolicy().hasHeightForWidth())
        self.connections.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(143, 240, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(143, 240, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(143, 240, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(133, 133, 133))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.connections.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("URW Bookman L")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(9)
        self.connections.setFont(font)
        self.connections.setStyleSheet("border-image: url(:/theme/circuit.jpg);\n"
"font: 75 italic 16pt \"URW Bookman L\";")
        self.connections.setObjectName("connections")
        self.gridLayout_2.addWidget(self.connections, 7, 1, 1, 2)
        self.connections.clicked.connect(connections)
#summary
        self.summary = QtWidgets.QPushButton(self.dashboardtab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.summary.sizePolicy().hasHeightForWidth())
        self.summary.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(143, 240, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(143, 240, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(143, 240, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(133, 133, 133))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.summary.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("URW Bookman L")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(9)
        self.summary.setFont(font)
        self.summary.setStyleSheet("border-image: url(:/theme/circuit.jpg);\n"
"font: 75 italic 16pt \"URW Bookman L\";")
        self.summary.setObjectName("summary")
        self.gridLayout_2.addWidget(self.summary, 0, 1, 1, 2)
        self.summary.clicked.connect(summary)
#config
        self.config = QtWidgets.QPushButton(self.dashboardtab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.config.sizePolicy().hasHeightForWidth())
        self.config.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(143, 240, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(143, 240, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(143, 240, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(133, 133, 133))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.config.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("URW Bookman L")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(9)
        self.config.setFont(font)
        self.config.setStyleSheet("border-image: url(:/theme/circuit.jpg);\n"
"font: 75 italic 16pt \"URW Bookman L\";")
        self.config.setObjectName("config")
        self.gridLayout_2.addWidget(self.config, 3, 2, 1, 1)
        self.config.clicked.connect(config)
#wallet
        self.wallet = QtWidgets.QPushButton(self.dashboardtab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wallet.sizePolicy().hasHeightForWidth())
        self.wallet.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(143, 240, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(143, 240, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(143, 240, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(133, 133, 133))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.wallet.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("URW Bookman L")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(9)
        self.wallet.setFont(font)
        self.wallet.setStyleSheet("border-image: url(:/theme/circuit.jpg);\n"
"font: 75 italic 16pt \"URW Bookman L\";")
        self.wallet.setObjectName("wallet")
        self.gridLayout_2.addWidget(self.wallet, 1, 0, 1, 3)
        self.wallet.clicked.connect(wallet)
#chain
        self.chain = QtWidgets.QPushButton(self.dashboardtab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chain.sizePolicy().hasHeightForWidth())
        self.chain.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(143, 240, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(143, 240, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(143, 240, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(133, 133, 133))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.chain.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("URW Bookman L")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(9)
        self.chain.setFont(font)
        self.chain.setStyleSheet("border-image: url(:/theme/circuit.jpg);\n"
"font: 75 italic 16pt \"URW Bookman L\";")
        self.chain.setObjectName("chain")
        self.gridLayout_2.addWidget(self.chain, 7, 0, 1, 1)
        self.chain.clicked.connect(chain)
#startcli
        self.startcli = QtWidgets.QPushButton(self.dashboardtab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startcli.sizePolicy().hasHeightForWidth())
        self.startcli.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(143, 240, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(143, 240, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(143, 240, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(133, 133, 133))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.startcli.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("URW Bookman L")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(9)
        self.startcli.setFont(font)
        self.startcli.setStyleSheet("border-image: url(:/theme/circuit.jpg);\n"
"font: 75 italic 16pt \"URW Bookman L\";")
        self.startcli.setObjectName("startcli")
        self.gridLayout_2.addWidget(self.startcli, 0, 0, 1, 1)
        self.startcli.clicked.connect(startcli)
#startgui
        self.startgui = QtWidgets.QPushButton(self.dashboardtab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startgui.sizePolicy().hasHeightForWidth())
        self.startgui.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(143, 240, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(143, 240, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(143, 240, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(133, 133, 133))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.startgui.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("URW Bookman L")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(9)
        self.startgui.setFont(font)
        self.startgui.setStyleSheet("border-image: url(:/theme/circuit.jpg);\n"
"font: 75 italic 16pt \"URW Bookman L\";")
        self.startgui.setObjectName("startgui")
        self.gridLayout_2.addWidget(self.startgui, 10, 2, 1, 1)
        self.startgui.clicked.connect(startgui)
#log
        self.log = QtWidgets.QPushButton(self.dashboardtab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.log.sizePolicy().hasHeightForWidth())
        self.log.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(143, 240, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(143, 240, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(143, 240, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(133, 133, 133))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.log.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("URW Bookman L")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(9)
        self.log.setFont(font)
        self.log.setStyleSheet("border-image: url(:/theme/circuit.jpg);\n"
"font: 75 italic 16pt \"URW Bookman L\";")
        self.log.setObjectName("log")
        self.gridLayout_2.addWidget(self.log, 3, 0, 1, 2)
        self.log.clicked.connect(log)
#challenges
        self.challenges = QtWidgets.QPushButton(self.dashboardtab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.challenges.sizePolicy().hasHeightForWidth())
        self.challenges.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(143, 240, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(143, 240, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(143, 240, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(133, 133, 133))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.challenges.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("URW Bookman L")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(9)
        self.challenges.setFont(font)
        self.challenges.setStyleSheet("border-image: url(:/theme/circuit.jpg);\n"
"font: 75 italic 16pt \"URW Bookman L\";")
        self.challenges.setObjectName("challenges")
        self.gridLayout_2.addWidget(self.challenges, 10, 0, 1, 2)
        self.challenges.clicked.connect(challenges)
#stoplayout
        self.stoplayout = QtWidgets.QVBoxLayout()
        self.stoplayout.setSpacing(0)
        self.stoplayout.setObjectName("stoplayout")
        self.stop = QtWidgets.QPushButton(self.dashboardtab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stop.sizePolicy().hasHeightForWidth())
        self.stop.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(143, 240, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(143, 240, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(143, 240, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(133, 133, 133))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.stop.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("URW Bookman L")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(9)
        self.stop.setFont(font)
        self.stop.setStyleSheet("border-image: url(:/theme/circuit.jpg);\n"
"font: 75 italic 16pt \"URW Bookman L\";")
        self.stop.setObjectName("stop")
        self.stoplayout.addWidget(self.stop)
        self.gridLayout_2.addLayout(self.stoplayout, 11, 0, 1, 1)
        self.stop.clicked.connect(stop)
#terminal
        self.terminal = QtWidgets.QPushButton(self.dashboardtab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.terminal.sizePolicy().hasHeightForWidth())
        self.terminal.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(143, 240, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(143, 240, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(143, 240, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(133, 133, 133))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.terminal.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("URW Bookman L")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(9)
        self.terminal.setFont(font)
        self.terminal.setStyleSheet("border-image: url(:/theme/circuit.jpg);\n"
"font: 75 italic 16pt \"URW Bookman L\";")
        self.terminal.setObjectName("terminal")
        self.gridLayout_2.addWidget(self.terminal, 11, 1, 1, 2)
        self.terminal.clicked.connect(terminal)
#END DASHBOARD TAB
        self.MainTab.addTab(self.dashboardtab, "")
#START KEYS TAB
        self.keys = QtWidgets.QWidget()
        self.keys.setObjectName("keys")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.keys)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setSpacing(0)
        self.gridLayout_7.setObjectName("gridLayout_7")
#genkey
        self.genkey = QtWidgets.QPushButton(self.keys)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.genkey.sizePolicy().hasHeightForWidth())
        self.genkey.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(143, 240, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(143, 240, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(143, 240, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(133, 133, 133))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.genkey.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("URW Bookman L")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(9)
        self.genkey.setFont(font)
        self.genkey.setStyleSheet("border-image: url(:/theme/circuit.jpg);\n"
"font: 75 italic 16pt \"URW Bookman L\";")
        self.genkey.setObjectName("genkey")
        self.gridLayout_7.addWidget(self.genkey, 3, 1, 1, 2)
        self.genkey.clicked.connect(genkey)
#gettransactions
        self.gettransactions = QtWidgets.QPushButton(self.keys)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gettransactions.sizePolicy().hasHeightForWidth())
        self.gettransactions.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(143, 240, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(143, 240, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(143, 240, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(133, 133, 133))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.gettransactions.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("URW Bookman L")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(9)
        self.gettransactions.setFont(font)
        self.gettransactions.setStyleSheet("border-image: url(:/theme/circuit.jpg);\n"
"font: 75 italic 16pt \"URW Bookman L\";")
        self.gettransactions.setObjectName("gettransactions")
        self.gridLayout_7.addWidget(self.gettransactions, 0, 1, 1, 2)
        self.gettransactions.clicked.connect(gettransactions)
#getaddress
        self.getaddress = QtWidgets.QPushButton(self.keys)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.getaddress.sizePolicy().hasHeightForWidth())
        self.getaddress.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(143, 240, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(143, 240, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(143, 240, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(133, 133, 133))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.getaddress.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("URW Bookman L")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(9)
        self.getaddress.setFont(font)
        self.getaddress.setStyleSheet("border-image: url(:/theme/circuit.jpg);\n"
"font: 75 italic 16pt \"URW Bookman L\";")
        self.getaddress.setObjectName("getaddress")
        self.gridLayout_7.addWidget(self.getaddress, 0, 0, 1, 1)
        self.getaddress.clicked.connect(getaddress)
#mnemonic
        self.mnemonic = QtWidgets.QPushButton(self.keys)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mnemonic.sizePolicy().hasHeightForWidth())
        self.mnemonic.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(143, 240, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(143, 240, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(143, 240, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(133, 133, 133))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.mnemonic.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("URW Bookman L")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(9)
        self.mnemonic.setFont(font)
        self.mnemonic.setStyleSheet("border-image: url(:/theme/circuit.jpg);\n"
"font: 75 italic 16pt \"URW Bookman L\";")
        self.mnemonic.setObjectName("mnemonic")
        self.gridLayout_7.addWidget(self.mnemonic, 5, 2, 1, 1)
        self.mnemonic.clicked.connect(mnemonic)
#genandprintkey
        self.genandprintkey = QtWidgets.QPushButton(self.keys)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.genandprintkey.sizePolicy().hasHeightForWidth())
        self.genandprintkey.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(143, 240, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(143, 240, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(143, 240, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(133, 133, 133))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.genandprintkey.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("URW Bookman L")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(9)
        self.genandprintkey.setFont(font)
        self.genandprintkey.setStyleSheet("border-image: url(:/theme/circuit.jpg);\n"
"font: 75 italic 16pt \"URW Bookman L\";")
        self.genandprintkey.setObjectName("genandprintkey")
        self.gridLayout_7.addWidget(self.genandprintkey, 5, 0, 1, 2)
        self.genandprintkey.clicked.connect(genandprintkey)
#addkey
        self.addkey = QtWidgets.QPushButton(self.keys)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addkey.sizePolicy().hasHeightForWidth())
        self.addkey.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(143, 240, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(143, 240, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(143, 240, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(133, 133, 133))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.addkey.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("URW Bookman L")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(9)
        self.addkey.setFont(font)
        self.addkey.setStyleSheet("border-image: url(:/theme/circuit.jpg);\n"
"font: 75 italic 16pt \"URW Bookman L\";")
        self.addkey.setObjectName("addkey")
        self.gridLayout_7.addWidget(self.addkey, 3, 0, 1, 1)
        self.addkey.clicked.connect(addkey)
#keysshow
        self.keysshow = QtWidgets.QPushButton(self.keys)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.keysshow.sizePolicy().hasHeightForWidth())
        self.keysshow.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(133, 133, 133))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.keysshow.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("URW Bookman L")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(9)
        self.keysshow.setFont(font)
        self.keysshow.setStyleSheet("border-image: url(:/theme/circuit.jpg);\n"
"font: 75 italic 16pt \"URW Bookman L\";")
        self.keysshow.setObjectName("keysshow")
        self.gridLayout_7.addWidget(self.keysshow, 2, 0, 1, 3)
        self.keysshow.clicked.connect(keysshow)
#END KEYS TAB
        self.MainTab.addTab(self.keys, "")
#START PORTS TAB
        self.portstab = QtWidgets.QWidget()
        self.portstab.setObjectName("portstab")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.portstab)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setSpacing(0)
        self.gridLayout_6.setObjectName("gridLayout_6")
#closeallport
        self.closeallport = QtWidgets.QPushButton(self.portstab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.closeallport.sizePolicy().hasHeightForWidth())
        self.closeallport.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(133, 133, 133))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.closeallport.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("URW Bookman L")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(9)
        self.closeallport.setFont(font)
        self.closeallport.setStyleSheet("border-image: url(:/theme/circuit.jpg);\n"
"font: 75 italic 16pt \"URW Bookman L\";")
        self.closeallport.setObjectName("closeallport")
        self.gridLayout_6.addWidget(self.closeallport, 6, 0, 1, 3)
        self.closeallport.clicked.connect(closeallport)
#closefullnodeport
        self.closefullnodeport = QtWidgets.QPushButton(self.portstab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.closefullnodeport.sizePolicy().hasHeightForWidth())
        self.closefullnodeport.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(133, 133, 133))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.closefullnodeport.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("URW Bookman L")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(9)
        self.closefullnodeport.setFont(font)
        self.closefullnodeport.setStyleSheet("border-image: url(:/theme/circuit.jpg);\n"
"font: 75 italic 16pt \"URW Bookman L\";")
        self.closefullnodeport.setObjectName("closefullnodeport")
        self.gridLayout_6.addWidget(self.closefullnodeport, 0, 2, 1, 1)
        self.closefullnodeport.clicked.connect(closefullnodeport)
#listports
        self.listports = QtWidgets.QPushButton(self.portstab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listports.sizePolicy().hasHeightForWidth())
        self.listports.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(133, 133, 133))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.listports.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("URW Bookman L")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(9)
        self.listports.setFont(font)
        self.listports.setStyleSheet("border-image: url(:/theme/circuit.jpg);\n"
"font: 75 italic 16pt \"URW Bookman L\";")
        self.listports.setObjectName("listports")
        self.gridLayout_6.addWidget(self.listports, 0, 0, 1, 2)
        self.listports.clicked.connect(listports)
#closefarmerport
        self.closefarmerport = QtWidgets.QPushButton(self.portstab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.closefarmerport.sizePolicy().hasHeightForWidth())
        self.closefarmerport.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(133, 133, 133))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.closefarmerport.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("URW Bookman L")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(9)
        self.closefarmerport.setFont(font)
        self.closefarmerport.setStyleSheet("border-image: url(:/theme/circuit.jpg);\n"
"font: 75 italic 16pt \"URW Bookman L\";")
        self.closefarmerport.setObjectName("closefarmerport")
        self.gridLayout_6.addWidget(self.closefarmerport, 1, 0, 1, 1)
        self.closefarmerport.clicked.connect(closefarmerport)
#closewalletport
        self.closewalletport = QtWidgets.QPushButton(self.portstab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.closewalletport.sizePolicy().hasHeightForWidth())
        self.closewalletport.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(133, 133, 133))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.closewalletport.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("URW Bookman L")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(9)
        self.closewalletport.setFont(font)
        self.closewalletport.setStyleSheet("border-image: url(:/theme/circuit.jpg);\n"
"font: 75 italic 16pt \"URW Bookman L\";")
        self.closewalletport.setObjectName("closewalletport")
        self.gridLayout_6.addWidget(self.closewalletport, 4, 2, 1, 1)
        self.closewalletport.clicked.connect(closewalletport)
#closeharvesterport
        self.closeharvesterport = QtWidgets.QPushButton(self.portstab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.closeharvesterport.sizePolicy().hasHeightForWidth())
        self.closeharvesterport.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(133, 133, 133))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.closeharvesterport.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("URW Bookman L")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(9)
        self.closeharvesterport.setFont(font)
        self.closeharvesterport.setStyleSheet("border-image: url(:/theme/circuit.jpg);\n"
"font: 75 italic 16pt \"URW Bookman L\";")
        self.closeharvesterport.setObjectName("closeharvesterport")
        self.gridLayout_6.addWidget(self.closeharvesterport, 1, 1, 1, 2)
        self.closeharvesterport.clicked.connect(closeharvesterport)
#closedaemonport
        self.closedaemonport = QtWidgets.QPushButton(self.portstab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.closedaemonport.sizePolicy().hasHeightForWidth())
        self.closedaemonport.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(133, 133, 133))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.closedaemonport.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("URW Bookman L")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(9)
        self.closedaemonport.setFont(font)
        self.closedaemonport.setStyleSheet("border-image: url(:/theme/circuit.jpg);\n"
"font: 75 italic 16pt \"URW Bookman L\";")
        self.closedaemonport.setObjectName("closedaemonport")
        self.gridLayout_6.addWidget(self.closedaemonport, 4, 0, 1, 2)
        self.closedaemonport.clicked.connect(closedaemonport)
#END PORTS TAB
        self.MainTab.addTab(self.portstab, "")
#START INSTALL TAB
        self.installtab = QtWidgets.QWidget()
        self.installtab.setObjectName("installtab")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.installtab)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
#installcli
        self.installcli = QtWidgets.QPushButton(self.installtab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.installcli.sizePolicy().hasHeightForWidth())
        self.installcli.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(133, 133, 133))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.installcli.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("URW Bookman L")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(9)
        self.installcli.setFont(font)
        self.installcli.setStyleSheet("border-image: url(:/theme/circuit.jpg);\n"
"font: 75 italic 16pt \"URW Bookman L\";")
        self.installcli.setObjectName("installcli")
        self.gridLayout_4.addWidget(self.installcli, 0, 0, 1, 1)
        self.installcli.clicked.connect(installcli)
#installgui
        self.installgui = QtWidgets.QPushButton(self.installtab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.installgui.sizePolicy().hasHeightForWidth())
        self.installgui.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(133, 133, 133))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.installgui.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("URW Bookman L")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(9)
        self.installgui.setFont(font)
        self.installgui.setStyleSheet("border-image: url(:/theme/circuit.jpg);\n"
"font: 75 italic 16pt \"URW Bookman L\";")
        self.installgui.setObjectName("installgui")
        self.gridLayout_4.addWidget(self.installgui, 1, 0, 1, 1)
        self.installgui.clicked.connect(installgui)
#version
        self.version = QtWidgets.QPushButton(self.installtab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.version.sizePolicy().hasHeightForWidth())
        self.version.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(133, 133, 133))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.version.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("URW Bookman L")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(9)
        self.version.setFont(font)
        self.version.setStyleSheet("border-image: url(:/theme/circuit.jpg);\n"
"font: 75 italic 16pt \"URW Bookman L\";")
        self.version.setObjectName("version")
        self.gridLayout_4.addWidget(self.version, 0, 1, 2, 1)
        self.version.clicked.connect(version)
#END INSTALL TAB
        self.MainTab.addTab(self.installtab, "")
#START UNINSTALL TAB
        self.uninstalltab = QtWidgets.QWidget()
        self.uninstalltab.setObjectName("uninstalltab")
        self.updatelayout = QtWidgets.QGridLayout(self.uninstalltab)
        self.updatelayout.setContentsMargins(0, 0, 0, 0)
        self.updatelayout.setSpacing(0)
        self.updatelayout.setObjectName("updatelayout")
#uninstallclient
        self.uninstallclient = QtWidgets.QPushButton(self.uninstalltab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uninstallclient.sizePolicy().hasHeightForWidth())
        self.uninstallclient.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(133, 133, 133))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.uninstallclient.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("URW Bookman L")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(9)
        self.uninstallclient.setFont(font)
        self.uninstallclient.setStyleSheet("border-image: url(:/theme/circuit.jpg);\n"
"font: 75 italic 16pt \"URW Bookman L\";")
        self.uninstallclient.setObjectName("uninstallclient")
        self.updatelayout.addWidget(self.uninstallclient, 1, 1, 1, 1)
        self.uninstallclient.clicked.connect(uninstallclient)
#updateclient
        self.updateclient = QtWidgets.QPushButton(self.uninstalltab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.updateclient.sizePolicy().hasHeightForWidth())
        self.updateclient.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(133, 133, 133))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.updateclient.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("URW Bookman L")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(9)
        self.updateclient.setFont(font)
        self.updateclient.setStyleSheet("border-image: url(:/theme/circuit.jpg);\n"
"font: 75 italic 16pt \"URW Bookman L\";")
        self.updateclient.setObjectName("updateclient")
        self.updatelayout.addWidget(self.updateclient, 0, 1, 1, 2)
        self.updateclient.clicked.connect(updateclient)
#deleteclient
        self.deleteclient = QtWidgets.QPushButton(self.uninstalltab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deleteclient.sizePolicy().hasHeightForWidth())
        self.deleteclient.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(133, 133, 133))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.deleteclient.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("URW Bookman L")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(9)
        self.deleteclient.setFont(font)
        self.deleteclient.setStyleSheet("border-image: url(:/theme/circuit.jpg);\n"
"font: 75 italic 16pt \"URW Bookman L\";")
        self.deleteclient.setObjectName("deleteclient")
        self.updatelayout.addWidget(self.deleteclient, 1, 2, 1, 1)
        self.deleteclient.clicked.connect(deleteclient)
#END UNINSTALL TAB
        self.MainTab.addTab(self.uninstalltab, "")
#TAB LAYOUT
        self.gridLayoutmain.addWidget(self.MainTab, 0, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayoutmain, 1, 1, 1, 1)
        SpareWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(SpareWindow)
        self.MainTab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(SpareWindow)

    def retranslateUi(self, SpareWindow):
        _translate = QtCore.QCoreApplication.translate
        SpareWindow.setWindowTitle(_translate("SpareWindow", "Spare"))
        self.connections.setText(_translate("SpareWindow", "Connections"))
        self.summary.setText(_translate("SpareWindow", "Farm Summary"))
        self.config.setText(_translate("SpareWindow", "Config"))
        self.wallet.setText(_translate("SpareWindow", "Show Spare Wallet"))
        self.chain.setText(_translate("SpareWindow", "State Of Spare"))
        self.startcli.setText(_translate("SpareWindow", "Start-CLI"))
        self.startgui.setText(_translate("SpareWindow", "Start-GUI"))
        self.log.setText(_translate("SpareWindow", "Log"))
        self.challenges.setText(_translate("SpareWindow", "Challenges"))
        self.stop.setText(_translate("SpareWindow", "Stop"))
        self.terminal.setText(_translate("SpareWindow", "Open Terminal"))
        self.MainTab.setTabText(self.MainTab.indexOf(self.dashboardtab), _translate("SpareWindow", "Dashboard"))
        self.genkey.setText(_translate("SpareWindow", "Generate Key"))
        self.gettransactions.setText(_translate("SpareWindow", "Get Transactions"))
        self.getaddress.setText(_translate("SpareWindow", "Get Address"))
        self.mnemonic.setText(_translate("SpareWindow", "Show Mnemonic"))
        self.genandprintkey.setText(_translate("SpareWindow", "Generate And Print Key"))
        self.addkey.setText(_translate("SpareWindow", "Add Key"))
        self.keysshow.setText(_translate("SpareWindow", "Spare Keys Show"))
        self.MainTab.setTabText(self.MainTab.indexOf(self.keys), _translate("SpareWindow", "Wallet and Keys"))
        self.closeallport.setText(_translate("SpareWindow", "Close All Ports"))
        self.closefullnodeport.setText(_translate("SpareWindow", "Close Full-Node 58444"))
        self.listports.setText(_translate("SpareWindow", "List Active PIDs"))
        self.closefarmerport.setText(_translate("SpareWindow", "Close Farmer 58447"))
        self.closewalletport.setText(_translate("SpareWindow", "Close Wallet 58449"))
        self.closeharvesterport.setText(_translate("SpareWindow", "Close Harvester 58448"))
        self.closedaemonport.setText(_translate("SpareWindow", "Close Daemon 55500"))
        self.MainTab.setTabText(self.MainTab.indexOf(self.portstab), _translate("SpareWindow", "Ports"))
        self.installcli.setText(_translate("SpareWindow", "Install CLI"))
        self.installgui.setText(_translate("SpareWindow", "Install GUI"))
        self.version.setText(_translate("SpareWindow", "Spare Version"))
        self.MainTab.setTabText(self.MainTab.indexOf(self.installtab), _translate("SpareWindow", "Install"))
        self.uninstallclient.setText(_translate("SpareWindow", "UnInstall Spare"))
        self.updateclient.setText(_translate("SpareWindow", "Update Spare"))
        self.deleteclient.setText(_translate("SpareWindow", "Delete Spare"))
        self.MainTab.setTabText(self.MainTab.indexOf(self.uninstalltab), _translate("SpareWindow", "Update/Uninstall"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SpareWindow = QtWidgets.QMainWindow()
    ui = Ui_SpareWindow()
    ui.setupUi(SpareWindow)
    SpareWindow.show()
    sys.exit(app.exec_()) 
