from PyQt5 import QtCore, QtGui, QtWidgets
import os
import sys
import subprocess
import plow_rc


def updateclient():
    os.system('echo "Lets get Ssd-Coin updated for you." ; cd ~/ssdcoin-blockchain ; . ./activate ; ssdcoin stop all ; deactivate ; sudo kill -9 $(sudo lsof -t -i:26400,29448,29449,29447,29444) ; cd ~/ ; mkdir ~/plow ; mkdir ~/plow/old-config ; rm -f --recursive -d ~/plow/old-config/.ssdcoin ; echo "Saving Mainnet folder in ~plow/old-config" ; mv ~/.ssdcoin -t ~/plow/old-config/ ; rm -f --recursive -d ~/ssdcoin-blockchain ; git clone https://github.com/ZeDon-SP/ssdcoin-blockchain.git ; cd ~/ssdcoin-blockchain ; sh install.sh ; . ./activate ; ssdcoin init ; cd ~/plow/old-config/.ssdcoin/mainnet ; mv db wallet -t ~/.ssdcoin/mainnet ; cd ~/ssdcoin-blockchain ; ssdcoin start farmer ; echo "Ssd-Coin has been Updated! The old Mainnet folder is saved in ~/plow/old-config, Add Your Plot Directories!" ; xdg-open ~/.ssdcoin/mainnet/config/config.yaml ; xdg-open ~/plow/plot-directories.yaml')
    
def installcli():
    os.system('echo "Lets get Ssd-Coin installed for you." ; cd ~/ ; sudo kill -9 $(sudo lsof -t -i:26400,29448,29449,29447,29444) ; git clone https://github.com/ZeDon-SP/ssdcoin-blockchain.git ; cd ~/ssdcoin-blockchain ; sh install.sh ; . ./activate ; ssdcoin init ; cd ~/plow/old-config/.ssdcoin/mainnet ; mv db wallet -t ~/.ssdcoin/mainnet ; cd ~/ssdcoin-blockchain ; ssdcoin keys add ; ssdcoin start farmer ; echo "Ssd-Coin has been installed, Add Your Plot Directories!!" ; xdg-open ~/.ssdcoin/mainnet/config/config.yaml ; xdg-open ~/plow/plot-directories.yaml')
    
#uninstall
def uninstallclient():
    os.system('echo "Lets get Ssd-Coin uninstalled for you." ; cd ~/ssdcoin-blockchain ; . ./activate ; ssdcoin stop all ; deactivate ; cd ~/ ; mkdir ~/plow ; mkdir ~/plow/old-config ; rm -f --recursive -d ~/plow/old-config/.ssdcoin ; mv ~/.ssdcoin -t ~/plow/old-config/ ; rm -f --recursive -d ~/ssdcoin-blockchain ; echo "Ssd-Coin has been Uninstalled. Old Mainnet folder is saved in ~/plow/old-config"')
    
def deleteclient():
    os.system('echo "Lets get Ssd-Coin deleted for you." ; cd ~/ ; mkdir ~/plow ; mkdir ~/plow/old-config ; rm -f --recursive -d ~/plow/old-config/.ssdcoin ; mv ~/.ssdcoin -t ~/plow/old-config/ ; rm -f --recursive -d ~/ssdcoin-blockchain ; echo "Ssd-Coin has been Deleted. The old Mainnet folder has been saved in ~/plow/old-config"') 

def keysshow():
    os.system('echo "Getting Ssd-Coin Fingerprint, Pool & Farmer Public Plot Keys..." ; cd ~/ssdcoin-blockchain ; . ./activate ; ssdcoin keys show')
    
def mnemonic():
    os.system('echo "Getting Active Ssd-Coin Mnemonic Key..." ; cd ~/ssdcoin-blockchain ; . ./activate ; ssdcoin keys show --show-mnemonic-seed')
	
def genandprintkey():
    os.system('echo "Generating and Printing New Ssd-Coin Mnemonic Key..." ; cd ~/ssdcoin-blockchain ; . ./activate ; ssdcoin generate_and_print')

def addkey():
    os.system('echo "Please Wait For Prompt To Add Existing Ssd-Coin Keys..." ; cd ~/ssdcoin-blockchain ; . ./activate ; ssdcoin keys add')
	
def genkey():
    os.system('echo "Generating New Ssd-Coin Mnemonic key..." ; cd ~/ssdcoin-blockchain ; . ./activate ; ssdcoin keys generate')

def stop():
    os.system('echo "Stopping Ssd-Coin..." ; cd ~/ssdcoin-blockchain ; . ./activate ; ssdcoin stop all')
	
def version():
    os.system('echo "Ssd-Coin Verion Number..." ; cd ~/ssdcoin-blockchain ; . ./activate ; ssdcoin version')

def startcli():
    os.system('echo "Starting Ssd-Coin..." ; cd ~/ssdcoin-blockchain ; . ./activate ; ssdcoin stop all ; deactivate ; cd ~/ ; cd ~/ssdcoin-blockchain ; . ./activate ; ssdcoin start farmer')

def chain():
    os.system('echo "Getting The State Of Ssd-Coin Blockchain..." ; cd ~/ssdcoin-blockchain ; . ./activate ; ssdcoin show -s')

def connections():
    os.system('echo "Getting Ssd-Coin Peer Connections..." ; cd ~/ssdcoin-blockchain ; . ./activate ; ssdcoin show -c')

def wallet():
    os.system('echo "Ssd-Coin Wallet Is Loading..." ; cd ~/ssdcoin-blockchain ; . ./activate ; ssdcoin wallet show')

def getaddress():
    os.system('echo "Getting Ssd-Coin Address..." ; cd ~/ssdcoin-blockchain ; . ./activate ; ssdcoin wallet get_address')

def gettransactions():
    os.system('echo "Getting Ssd-Coin Transactions..." ; cd ~/ssdcoin-blockchain ; . ./activate ; ssdcoin wallet get_transactions')
	
def summary():
    os.system('echo "Ssd-Coin Farm Summary Loading..." ; cd ~/ssdcoin-blockchain ; . ./activate ; ssdcoin farm summary')
	
def challenges():
    os.system('echo "Ssd-Coin Challenges Loading..." ; cd ~/ssdcoin-blockchain ; . ./activate ; ssdcoin farm challenges ; echo "End Of Challenges"')
    
def config():
    os.system('echo "Opening Ssd-Coin Config File..." ; xdg-open ~/.ssdcoin/mainnet/config/config.yaml')
    
def log():
    os.system('echo "Opening Ssd-Coin Log File..." ; xdg-open ~/.ssdcoin/mainnet/log/debug.log')
    
def startgui():
    os.system('echo "Starting Ssd-Coin-GUI..." ; cd ~/ssdcoin-blockchain ; . ./activate ; cd ssdcoin-blockchian-gui ; npm run electron')  
    
def installgui():
    os.system('echo "Lets get Ssd-Coin-GUI installed for you." ; cd ~/ssdcoin-blockchain ; . ./activate ; sh install-gui.sh ; cd ssdcoin-blockchian-gui ; npm run electron')
  
def closedaemonport():
    os.system('echo "Closing Ssd-Coin Daemon Port..." ; sudo kill -9 $(sudo lsof -t -i:26400) ; echo "Process IDs On Daemon Port 26400 Closed"')             

def closefarmerport():
    os.system('echo "Closing Ssd-Coin Farmer Port..." ; sudo kill -9 $(sudo lsof -t -i:29447) ; echo "Process IDs On Farmer Port 29447 Closed"')

def closeharvesterport():
    os.system('echo "Closing Ssd-Coin Harvester Port..." ; sudo kill -9 $(sudo lsof -t -i:29448) ; echo "Process IDs On Harvester Port 29448 Closed"')

def closefullnodeport():
    os.system('echo "Closing Ssd-Coin Full-Node Port..." ; sudo kill -9 $(sudo lsof -t -i:29444) ; echo "Process IDs On Full Node Port 29444 Closed"')

def closewalletport():
    os.system('echo "Closing Ssd-Coin Wallet Port..." ; sudo kill -9 $(sudo lsof -t -i:29449) ; echo "Process IDs on Wallet Port 29449 Closed"')

def listports():
    os.system('echo "List of All Ssd-Coin Process IDs for Ports, Daemon 26400, Harvester 29448, Wallet 29449, Farmer 29447, Full Node 29444." ; echo "For more details on Active Process IDs, use Extras Tab on Main Window." ; sudo lsof -t -i:26400,29448,29449,29447,29444')

def closeallport():
    os.system('echo "Closing All Ssd-Coin Ports..." ; sudo kill -9 $(sudo lsof -t -i:26400,29448,29449,29447,29444) ; echo "All Process IDs on Ports, Daemon 26400, Harvester 29448, Wallet 29449, Farmer 29447, Full Node 29444, are closed"')

def terminal():
    subprocess.call('echo "Opening Terminal in Ssd-Coin Folder" ; cd ~/ssdcoin-blockchain ; x-terminal-emulator -- ', shell =True)


class Ui_SsdCoinWindow(object):
    def setupUi(self, SsdCoinWindow):
        SsdCoinWindow.setObjectName("SsdCoinWindow")
        SsdCoinWindow.resize(483, 320)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(28, 113, 216))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(102, 171, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(65, 142, 235))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(14, 57, 108))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(19, 75, 144))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(7, 69, 88))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(141, 184, 235))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(28, 113, 216))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(102, 171, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(65, 142, 235))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(14, 57, 108))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(19, 75, 144))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(7, 69, 88))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(141, 184, 235))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(14, 57, 108))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(28, 113, 216))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(102, 171, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(65, 142, 235))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(14, 57, 108))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(19, 75, 144))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(14, 57, 108))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(14, 57, 108))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(7, 69, 88))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(7, 69, 88))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(28, 113, 216))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
#START MAIN WINDOW
        SsdCoinWindow.setPalette(palette)
#ICON
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/theme/plow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        SsdCoinWindow.setWindowIcon(icon)
#MAIN WINDOWS SPECS
        self.centralwidget = QtWidgets.QWidget(SsdCoinWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayoutmain = QtWidgets.QGridLayout()
        self.gridLayoutmain.setSpacing(0)
        self.gridLayoutmain.setObjectName("gridLayoutmain")
        self.MainTab = QtWidgets.QTabWidget(self.centralwidget)
        self.MainTab.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MainTab.sizePolicy().hasHeightForWidth())
        self.MainTab.setSizePolicy(sizePolicy)
#END MAIN WINDOW SPECS
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(25, 186, 227))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(113, 226, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(69, 206, 241))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(12, 93, 113))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(17, 124, 151))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(119, 118, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(140, 220, 241))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(25, 186, 227))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(113, 226, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(69, 206, 241))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(12, 93, 113))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(17, 124, 151))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(119, 118, 123))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(140, 220, 241))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(12, 93, 113))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(25, 186, 227))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(113, 226, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(69, 206, 241))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(12, 93, 113))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(17, 124, 151))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(12, 93, 113))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(12, 93, 113))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(25, 186, 227))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.MainTab.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Fira Sans")
        font.setBold(True)
        font.setWeight(75)
        self.MainTab.setFont(font)
        self.MainTab.setMouseTracking(True)
        self.MainTab.setTabletTracking(True)
        self.MainTab.setAutoFillBackground(True)
        self.MainTab.setStyleSheet("")
        self.MainTab.setObjectName("MainTab")
#START DASHBOARD TAB
        self.dashboardtab = QtWidgets.QWidget()
        self.dashboardtab.setObjectName("dashboardtab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.dashboardtab)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
#connections
        self.connections = QtWidgets.QPushButton(self.dashboardtab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.connections.sizePolicy().hasHeightForWidth())
        self.connections.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(143, 240, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(143, 240, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(143, 240, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(133, 133, 133))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.connections.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("URW Bookman L")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(9)
        self.connections.setFont(font)
        self.connections.setStyleSheet("border-image: url(:/theme/circuit.jpg);\n"
"font: 75 italic 16pt \"URW Bookman L\";")
        self.connections.setObjectName("connections")
        self.gridLayout_2.addWidget(self.connections, 7, 1, 1, 2)
        self.connections.clicked.connect(connections)
#summary
        self.summary = QtWidgets.QPushButton(self.dashboardtab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.summary.sizePolicy().hasHeightForWidth())
        self.summary.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(143, 240, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(143, 240, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(143, 240, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(133, 133, 133))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.summary.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("URW Bookman L")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(9)
        self.summary.setFont(font)
        self.summary.setStyleSheet("border-image: url(:/theme/circuit.jpg);\n"
"font: 75 italic 16pt \"URW Bookman L\";")
        self.summary.setObjectName("summary")
        self.gridLayout_2.addWidget(self.summary, 0, 1, 1, 2)
        self.summary.clicked.connect(summary)
#config
        self.config = QtWidgets.QPushButton(self.dashboardtab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.config.sizePolicy().hasHeightForWidth())
        self.config.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(143, 240, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(143, 240, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(143, 240, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(133, 133, 133))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.config.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("URW Bookman L")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(9)
        self.config.setFont(font)
        self.config.setStyleSheet("border-image: url(:/theme/circuit.jpg);\n"
"font: 75 italic 16pt \"URW Bookman L\";")
        self.config.setObjectName("config")
        self.gridLayout_2.addWidget(self.config, 3, 2, 1, 1)
        self.config.clicked.connect(config)
#wallet
        self.wallet = QtWidgets.QPushButton(self.dashboardtab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wallet.sizePolicy().hasHeightForWidth())
        self.wallet.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(143, 240, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(143, 240, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(143, 240, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(133, 133, 133))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.wallet.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("URW Bookman L")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(9)
        self.wallet.setFont(font)
        self.wallet.setStyleSheet("border-image: url(:/theme/circuit.jpg);\n"
"font: 75 italic 16pt \"URW Bookman L\";")
        self.wallet.setObjectName("wallet")
        self.gridLayout_2.addWidget(self.wallet, 1, 0, 1, 3)
        self.wallet.clicked.connect(wallet)
#chain
        self.chain = QtWidgets.QPushButton(self.dashboardtab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chain.sizePolicy().hasHeightForWidth())
        self.chain.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(143, 240, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(143, 240, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(143, 240, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(133, 133, 133))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.chain.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("URW Bookman L")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(9)
        self.chain.setFont(font)
        self.chain.setStyleSheet("border-image: url(:/theme/circuit.jpg);\n"
"font: 75 italic 16pt \"URW Bookman L\";")
        self.chain.setObjectName("chain")
        self.gridLayout_2.addWidget(self.chain, 7, 0, 1, 1)
        self.chain.clicked.connect(chain)
#startcli
        self.startcli = QtWidgets.QPushButton(self.dashboardtab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startcli.sizePolicy().hasHeightForWidth())
        self.startcli.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(143, 240, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(143, 240, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(143, 240, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(133, 133, 133))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.startcli.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("URW Bookman L")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(9)
        self.startcli.setFont(font)
        self.startcli.setStyleSheet("border-image: url(:/theme/circuit.jpg);\n"
"font: 75 italic 16pt \"URW Bookman L\";")
        self.startcli.setObjectName("startcli")
        self.gridLayout_2.addWidget(self.startcli, 0, 0, 1, 1)
        self.startcli.clicked.connect(startcli)
#startgui
        self.startgui = QtWidgets.QPushButton(self.dashboardtab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startgui.sizePolicy().hasHeightForWidth())
        self.startgui.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(143, 240, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(143, 240, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(143, 240, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(133, 133, 133))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.startgui.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("URW Bookman L")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(9)
        self.startgui.setFont(font)
        self.startgui.setStyleSheet("border-image: url(:/theme/circuit.jpg);\n"
"font: 75 italic 16pt \"URW Bookman L\";")
        self.startgui.setObjectName("startgui")
        self.gridLayout_2.addWidget(self.startgui, 10, 2, 1, 1)
        self.startgui.clicked.connect(startgui)
#log
        self.log = QtWidgets.QPushButton(self.dashboardtab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.log.sizePolicy().hasHeightForWidth())
        self.log.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(143, 240, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(143, 240, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(143, 240, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(133, 133, 133))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.log.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("URW Bookman L")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(9)
        self.log.setFont(font)
        self.log.setStyleSheet("border-image: url(:/theme/circuit.jpg);\n"
"font: 75 italic 16pt \"URW Bookman L\";")
        self.log.setObjectName("log")
        self.gridLayout_2.addWidget(self.log, 3, 0, 1, 2)
        self.log.clicked.connect(log)
#challenges
        self.challenges = QtWidgets.QPushButton(self.dashboardtab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.challenges.sizePolicy().hasHeightForWidth())
        self.challenges.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(143, 240, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(143, 240, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(143, 240, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(133, 133, 133))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.challenges.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("URW Bookman L")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(9)
        self.challenges.setFont(font)
        self.challenges.setStyleSheet("border-image: url(:/theme/circuit.jpg);\n"
"font: 75 italic 16pt \"URW Bookman L\";")
        self.challenges.setObjectName("challenges")
        self.gridLayout_2.addWidget(self.challenges, 10, 0, 1, 2)
        self.challenges.clicked.connect(challenges)
#stoplayout
        self.stoplayout = QtWidgets.QVBoxLayout()
        self.stoplayout.setSpacing(0)
        self.stoplayout.setObjectName("stoplayout")
        self.stop = QtWidgets.QPushButton(self.dashboardtab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stop.sizePolicy().hasHeightForWidth())
        self.stop.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(143, 240, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(143, 240, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(143, 240, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(133, 133, 133))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.stop.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("URW Bookman L")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(9)
        self.stop.setFont(font)
        self.stop.setStyleSheet("border-image: url(:/theme/circuit.jpg);\n"
"font: 75 italic 16pt \"URW Bookman L\";")
        self.stop.setObjectName("stop")
        self.stoplayout.addWidget(self.stop)
        self.gridLayout_2.addLayout(self.stoplayout, 11, 0, 1, 1)
        self.stop.clicked.connect(stop)
#terminal
        self.terminal = QtWidgets.QPushButton(self.dashboardtab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.terminal.sizePolicy().hasHeightForWidth())
        self.terminal.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(143, 240, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(143, 240, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(143, 240, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(133, 133, 133))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.terminal.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("URW Bookman L")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(9)
        self.terminal.setFont(font)
        self.terminal.setStyleSheet("border-image: url(:/theme/circuit.jpg);\n"
"font: 75 italic 16pt \"URW Bookman L\";")
        self.terminal.setObjectName("terminal")
        self.gridLayout_2.addWidget(self.terminal, 11, 1, 1, 2)
        self.terminal.clicked.connect(terminal)
#END DASHBOARD TAB
        self.MainTab.addTab(self.dashboardtab, "")
#START KEYS TAB
        self.keys = QtWidgets.QWidget()
        self.keys.setObjectName("keys")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.keys)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setSpacing(0)
        self.gridLayout_7.setObjectName("gridLayout_7")
#genkey
        self.genkey = QtWidgets.QPushButton(self.keys)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.genkey.sizePolicy().hasHeightForWidth())
        self.genkey.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(143, 240, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(143, 240, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(143, 240, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(133, 133, 133))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.genkey.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("URW Bookman L")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(9)
        self.genkey.setFont(font)
        self.genkey.setStyleSheet("border-image: url(:/theme/circuit.jpg);\n"
"font: 75 italic 16pt \"URW Bookman L\";")
        self.genkey.setObjectName("genkey")
        self.gridLayout_7.addWidget(self.genkey, 3, 1, 1, 2)
        self.genkey.clicked.connect(genkey)
#gettransactions
        self.gettransactions = QtWidgets.QPushButton(self.keys)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gettransactions.sizePolicy().hasHeightForWidth())
        self.gettransactions.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(143, 240, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(143, 240, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(143, 240, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(133, 133, 133))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.gettransactions.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("URW Bookman L")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(9)
        self.gettransactions.setFont(font)
        self.gettransactions.setStyleSheet("border-image: url(:/theme/circuit.jpg);\n"
"font: 75 italic 16pt \"URW Bookman L\";")
        self.gettransactions.setObjectName("gettransactions")
        self.gridLayout_7.addWidget(self.gettransactions, 0, 1, 1, 2)
        self.gettransactions.clicked.connect(gettransactions)
#getaddress
        self.getaddress = QtWidgets.QPushButton(self.keys)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.getaddress.sizePolicy().hasHeightForWidth())
        self.getaddress.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(143, 240, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(143, 240, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(143, 240, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(133, 133, 133))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.getaddress.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("URW Bookman L")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(9)
        self.getaddress.setFont(font)
        self.getaddress.setStyleSheet("border-image: url(:/theme/circuit.jpg);\n"
"font: 75 italic 16pt \"URW Bookman L\";")
        self.getaddress.setObjectName("getaddress")
        self.gridLayout_7.addWidget(self.getaddress, 0, 0, 1, 1)
        self.getaddress.clicked.connect(getaddress)
#mnemonic
        self.mnemonic = QtWidgets.QPushButton(self.keys)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mnemonic.sizePolicy().hasHeightForWidth())
        self.mnemonic.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(143, 240, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(143, 240, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(143, 240, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(133, 133, 133))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.mnemonic.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("URW Bookman L")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(9)
        self.mnemonic.setFont(font)
        self.mnemonic.setStyleSheet("border-image: url(:/theme/circuit.jpg);\n"
"font: 75 italic 16pt \"URW Bookman L\";")
        self.mnemonic.setObjectName("mnemonic")
        self.gridLayout_7.addWidget(self.mnemonic, 5, 2, 1, 1)
        self.mnemonic.clicked.connect(mnemonic)
#genandprintkey
        self.genandprintkey = QtWidgets.QPushButton(self.keys)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.genandprintkey.sizePolicy().hasHeightForWidth())
        self.genandprintkey.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(143, 240, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(143, 240, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(143, 240, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(133, 133, 133))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.genandprintkey.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("URW Bookman L")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(9)
        self.genandprintkey.setFont(font)
        self.genandprintkey.setStyleSheet("border-image: url(:/theme/circuit.jpg);\n"
"font: 75 italic 16pt \"URW Bookman L\";")
        self.genandprintkey.setObjectName("genandprintkey")
        self.gridLayout_7.addWidget(self.genandprintkey, 5, 0, 1, 2)
        self.genandprintkey.clicked.connect(genandprintkey)
#addkey
        self.addkey = QtWidgets.QPushButton(self.keys)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addkey.sizePolicy().hasHeightForWidth())
        self.addkey.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(143, 240, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(143, 240, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(143, 240, 164))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(133, 133, 133))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.addkey.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("URW Bookman L")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(9)
        self.addkey.setFont(font)
        self.addkey.setStyleSheet("border-image: url(:/theme/circuit.jpg);\n"
"font: 75 italic 16pt \"URW Bookman L\";")
        self.addkey.setObjectName("addkey")
        self.gridLayout_7.addWidget(self.addkey, 3, 0, 1, 1)
        self.addkey.clicked.connect(addkey)
#keysshow
        self.keysshow = QtWidgets.QPushButton(self.keys)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.keysshow.sizePolicy().hasHeightForWidth())
        self.keysshow.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(133, 133, 133))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.keysshow.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("URW Bookman L")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(9)
        self.keysshow.setFont(font)
        self.keysshow.setStyleSheet("border-image: url(:/theme/circuit.jpg);\n"
"font: 75 italic 16pt \"URW Bookman L\";")
        self.keysshow.setObjectName("keysshow")
        self.gridLayout_7.addWidget(self.keysshow, 2, 0, 1, 3)
        self.keysshow.clicked.connect(keysshow)
#END KEYS TAB
        self.MainTab.addTab(self.keys, "")
#START PORTS TAB
        self.portstab = QtWidgets.QWidget()
        self.portstab.setObjectName("portstab")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.portstab)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setSpacing(0)
        self.gridLayout_6.setObjectName("gridLayout_6")
#closeallport
        self.closeallport = QtWidgets.QPushButton(self.portstab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.closeallport.sizePolicy().hasHeightForWidth())
        self.closeallport.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(133, 133, 133))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.closeallport.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("URW Bookman L")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(9)
        self.closeallport.setFont(font)
        self.closeallport.setStyleSheet("border-image: url(:/theme/circuit.jpg);\n"
"font: 75 italic 16pt \"URW Bookman L\";")
        self.closeallport.setObjectName("closeallport")
        self.gridLayout_6.addWidget(self.closeallport, 6, 0, 1, 3)
        self.closeallport.clicked.connect(closeallport)
#closefullnodeport
        self.closefullnodeport = QtWidgets.QPushButton(self.portstab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.closefullnodeport.sizePolicy().hasHeightForWidth())
        self.closefullnodeport.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(133, 133, 133))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.closefullnodeport.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("URW Bookman L")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(9)
        self.closefullnodeport.setFont(font)
        self.closefullnodeport.setStyleSheet("border-image: url(:/theme/circuit.jpg);\n"
"font: 75 italic 16pt \"URW Bookman L\";")
        self.closefullnodeport.setObjectName("closefullnodeport")
        self.gridLayout_6.addWidget(self.closefullnodeport, 0, 2, 1, 1)
        self.closefullnodeport.clicked.connect(closefullnodeport)
#listports
        self.listports = QtWidgets.QPushButton(self.portstab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listports.sizePolicy().hasHeightForWidth())
        self.listports.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(133, 133, 133))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.listports.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("URW Bookman L")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(9)
        self.listports.setFont(font)
        self.listports.setStyleSheet("border-image: url(:/theme/circuit.jpg);\n"
"font: 75 italic 16pt \"URW Bookman L\";")
        self.listports.setObjectName("listports")
        self.gridLayout_6.addWidget(self.listports, 0, 0, 1, 2)
        self.listports.clicked.connect(listports)
#closefarmerport
        self.closefarmerport = QtWidgets.QPushButton(self.portstab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.closefarmerport.sizePolicy().hasHeightForWidth())
        self.closefarmerport.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(133, 133, 133))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.closefarmerport.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("URW Bookman L")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(9)
        self.closefarmerport.setFont(font)
        self.closefarmerport.setStyleSheet("border-image: url(:/theme/circuit.jpg);\n"
"font: 75 italic 16pt \"URW Bookman L\";")
        self.closefarmerport.setObjectName("closefarmerport")
        self.gridLayout_6.addWidget(self.closefarmerport, 1, 0, 1, 1)
        self.closefarmerport.clicked.connect(closefarmerport)
#closewalletport
        self.closewalletport = QtWidgets.QPushButton(self.portstab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.closewalletport.sizePolicy().hasHeightForWidth())
        self.closewalletport.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(133, 133, 133))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.closewalletport.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("URW Bookman L")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(9)
        self.closewalletport.setFont(font)
        self.closewalletport.setStyleSheet("border-image: url(:/theme/circuit.jpg);\n"
"font: 75 italic 16pt \"URW Bookman L\";")
        self.closewalletport.setObjectName("closewalletport")
        self.gridLayout_6.addWidget(self.closewalletport, 4, 2, 1, 1)
        self.closewalletport.clicked.connect(closewalletport)
#closeharvesterport
        self.closeharvesterport = QtWidgets.QPushButton(self.portstab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.closeharvesterport.sizePolicy().hasHeightForWidth())
        self.closeharvesterport.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(133, 133, 133))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.closeharvesterport.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("URW Bookman L")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(9)
        self.closeharvesterport.setFont(font)
        self.closeharvesterport.setStyleSheet("border-image: url(:/theme/circuit.jpg);\n"
"font: 75 italic 16pt \"URW Bookman L\";")
        self.closeharvesterport.setObjectName("closeharvesterport")
        self.gridLayout_6.addWidget(self.closeharvesterport, 1, 1, 1, 2)
        self.closeharvesterport.clicked.connect(closeharvesterport)
#closedaemonport
        self.closedaemonport = QtWidgets.QPushButton(self.portstab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.closedaemonport.sizePolicy().hasHeightForWidth())
        self.closedaemonport.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(133, 133, 133))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.closedaemonport.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("URW Bookman L")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(9)
        self.closedaemonport.setFont(font)
        self.closedaemonport.setStyleSheet("border-image: url(:/theme/circuit.jpg);\n"
"font: 75 italic 16pt \"URW Bookman L\";")
        self.closedaemonport.setObjectName("closedaemonport")
        self.gridLayout_6.addWidget(self.closedaemonport, 4, 0, 1, 2)
        self.closedaemonport.clicked.connect(closedaemonport)
#END PORTS TAB
        self.MainTab.addTab(self.portstab, "")
#START INSTALL TAB
        self.installtab = QtWidgets.QWidget()
        self.installtab.setObjectName("installtab")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.installtab)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
#installcli
        self.installcli = QtWidgets.QPushButton(self.installtab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.installcli.sizePolicy().hasHeightForWidth())
        self.installcli.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(133, 133, 133))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.installcli.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("URW Bookman L")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(9)
        self.installcli.setFont(font)
        self.installcli.setStyleSheet("border-image: url(:/theme/circuit.jpg);\n"
"font: 75 italic 16pt \"URW Bookman L\";")
        self.installcli.setObjectName("installcli")
        self.gridLayout_4.addWidget(self.installcli, 0, 0, 1, 1)
        self.installcli.clicked.connect(installcli)
#installgui
        self.installgui = QtWidgets.QPushButton(self.installtab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.installgui.sizePolicy().hasHeightForWidth())
        self.installgui.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(133, 133, 133))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.installgui.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("URW Bookman L")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(9)
        self.installgui.setFont(font)
        self.installgui.setStyleSheet("border-image: url(:/theme/circuit.jpg);\n"
"font: 75 italic 16pt \"URW Bookman L\";")
        self.installgui.setObjectName("installgui")
        self.gridLayout_4.addWidget(self.installgui, 1, 0, 1, 1)
        self.installgui.clicked.connect(installgui)
#version
        self.version = QtWidgets.QPushButton(self.installtab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.version.sizePolicy().hasHeightForWidth())
        self.version.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(133, 133, 133))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.version.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("URW Bookman L")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(9)
        self.version.setFont(font)
        self.version.setStyleSheet("border-image: url(:/theme/circuit.jpg);\n"
"font: 75 italic 16pt \"URW Bookman L\";")
        self.version.setObjectName("version")
        self.gridLayout_4.addWidget(self.version, 0, 1, 2, 1)
        self.version.clicked.connect(version)
#END INSTALL TAB
        self.MainTab.addTab(self.installtab, "")
#START UNINSTALL TAB
        self.uninstalltab = QtWidgets.QWidget()
        self.uninstalltab.setObjectName("uninstalltab")
        self.updatelayout = QtWidgets.QGridLayout(self.uninstalltab)
        self.updatelayout.setContentsMargins(0, 0, 0, 0)
        self.updatelayout.setSpacing(0)
        self.updatelayout.setObjectName("updatelayout")
#uninstallclient
        self.uninstallclient = QtWidgets.QPushButton(self.uninstalltab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uninstallclient.sizePolicy().hasHeightForWidth())
        self.uninstallclient.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(133, 133, 133))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.uninstallclient.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("URW Bookman L")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(9)
        self.uninstallclient.setFont(font)
        self.uninstallclient.setStyleSheet("border-image: url(:/theme/circuit.jpg);\n"
"font: 75 italic 16pt \"URW Bookman L\";")
        self.uninstallclient.setObjectName("uninstallclient")
        self.updatelayout.addWidget(self.uninstallclient, 1, 1, 1, 1)
        self.uninstallclient.clicked.connect(uninstallclient)
#updateclient
        self.updateclient = QtWidgets.QPushButton(self.uninstalltab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.updateclient.sizePolicy().hasHeightForWidth())
        self.updateclient.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(133, 133, 133))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.updateclient.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("URW Bookman L")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(9)
        self.updateclient.setFont(font)
        self.updateclient.setStyleSheet("border-image: url(:/theme/circuit.jpg);\n"
"font: 75 italic 16pt \"URW Bookman L\";")
        self.updateclient.setObjectName("updateclient")
        self.updatelayout.addWidget(self.updateclient, 0, 1, 1, 2)
        self.updateclient.clicked.connect(updateclient)
#deleteclient
        self.deleteclient = QtWidgets.QPushButton(self.uninstalltab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deleteclient.sizePolicy().hasHeightForWidth())
        self.deleteclient.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(133, 133, 133))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.deleteclient.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("URW Bookman L")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(9)
        self.deleteclient.setFont(font)
        self.deleteclient.setStyleSheet("border-image: url(:/theme/circuit.jpg);\n"
"font: 75 italic 16pt \"URW Bookman L\";")
        self.deleteclient.setObjectName("deleteclient")
        self.updatelayout.addWidget(self.deleteclient, 1, 2, 1, 1)
        self.deleteclient.clicked.connect(deleteclient)
#END UNINSTALL TAB
        self.MainTab.addTab(self.uninstalltab, "")
#TAB LAYOUT
        self.gridLayoutmain.addWidget(self.MainTab, 0, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayoutmain, 1, 1, 1, 1)
        SsdCoinWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(SsdCoinWindow)
        self.MainTab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(SsdCoinWindow)

    def retranslateUi(self, SsdCoinWindow):
        _translate = QtCore.QCoreApplication.translate
        SsdCoinWindow.setWindowTitle(_translate("SsdCoinWindow", "Ssd-Coin"))
        self.connections.setText(_translate("SsdCoinWindow", "Connections"))
        self.summary.setText(_translate("SsdCoinWindow", "Farm Summary"))
        self.config.setText(_translate("SsdCoinWindow", "Config"))
        self.wallet.setText(_translate("SsdCoinWindow", "Show Ssd-Coin Wallet"))
        self.chain.setText(_translate("SsdCoinWindow", "State Of Ssd-Coin"))
        self.startcli.setText(_translate("SsdCoinWindow", "Start-CLI"))
        self.startgui.setText(_translate("SsdCoinWindow", "Start-GUI"))
        self.log.setText(_translate("SsdCoinWindow", "Log"))
        self.challenges.setText(_translate("SsdCoinWindow", "Challenges"))
        self.stop.setText(_translate("SsdCoinWindow", "Stop"))
        self.terminal.setText(_translate("SsdCoinWindow", "Open Terminal"))
        self.MainTab.setTabText(self.MainTab.indexOf(self.dashboardtab), _translate("SsdCoinWindow", "Dashboard"))
        self.genkey.setText(_translate("SsdCoinWindow", "Generate Key"))
        self.gettransactions.setText(_translate("SsdCoinWindow", "Get Transactions"))
        self.getaddress.setText(_translate("SsdCoinWindow", "Get Address"))
        self.mnemonic.setText(_translate("SsdCoinWindow", "Show Mnemonic"))
        self.genandprintkey.setText(_translate("SsdCoinWindow", "Generate And Print Key"))
        self.addkey.setText(_translate("SsdCoinWindow", "Add Key"))
        self.keysshow.setText(_translate("SsdCoinWindow", "Ssd-Coin Keys Show"))
        self.MainTab.setTabText(self.MainTab.indexOf(self.keys), _translate("SsdCoinWindow", "Wallet and Keys"))
        self.closeallport.setText(_translate("SsdCoinWindow", "Close All Ports"))
        self.closefullnodeport.setText(_translate("SsdCoinWindow", "Close Full-Node 29444"))
        self.listports.setText(_translate("SsdCoinWindow", "List Active PIDs"))
        self.closefarmerport.setText(_translate("SsdCoinWindow", "Close Farmer 29447"))
        self.closewalletport.setText(_translate("SsdCoinWindow", "Close Wallet 29449"))
        self.closeharvesterport.setText(_translate("SsdCoinWindow", "Close Harvester 29448"))
        self.closedaemonport.setText(_translate("SsdCoinWindow", "Close Daemon 26400"))
        self.MainTab.setTabText(self.MainTab.indexOf(self.portstab), _translate("SsdCoinWindow", "Ports"))
        self.installcli.setText(_translate("SsdCoinWindow", "Install CLI"))
        self.installgui.setText(_translate("SsdCoinWindow", "Install GUI"))
        self.version.setText(_translate("SsdCoinWindow", "Ssd-Coin Version"))
        self.MainTab.setTabText(self.MainTab.indexOf(self.installtab), _translate("SsdCoinWindow", "Install"))
        self.uninstallclient.setText(_translate("SsdCoinWindow", "UnInstall Ssd-Coin"))
        self.updateclient.setText(_translate("SsdCoinWindow", "Update Ssd-Coin"))
        self.deleteclient.setText(_translate("SsdCoinWindow", "Delete Ssd-Coin"))
        self.MainTab.setTabText(self.MainTab.indexOf(self.uninstalltab), _translate("SsdCoinWindow", "Update/Uninstall"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SsdCoinWindow = QtWidgets.QMainWindow()
    ui = Ui_SsdCoinWindow()
    ui.setupUi(SsdCoinWindow)
    SsdCoinWindow.show()
    sys.exit(app.exec_()) 
