from PyQt5 import QtCore, QtGui, QtWidgets
import os
import sys
import plow_rc


def update():
    os.system('sh update')

def install():
    os.system('sh plowinstall.sh')

def installnoextras():
    os.system('sh install-no-extras.sh')

def uninstall():
    os.system('sh uninstall.sh')

def uninstallextras():
    os.system('sh uninstall-extras.sh')

def installall():
    os.system('sh All-Clients-Install.sh')

class Ui_PlowInstallerWindow(object):
    def setupUi(self, PlowInstallerWindow):
        PlowInstallerWindow.setObjectName("PlowInstallerWindow")
        PlowInstallerWindow.resize(450, 250)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(7, 69, 88))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(7, 69, 88))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(7, 69, 88))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(7, 69, 88))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        PlowInstallerWindow.setPalette(palette)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/theme/plow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        PlowInstallerWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(PlowInstallerWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(133, 133, 133))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
#START UPDATE TAB
        self.tabWidget.setPalette(palette)
        self.tabWidget.setObjectName("tabWidget")
        self.updatetab = QtWidgets.QWidget()
        self.updatetab.setObjectName("updatetab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.updatetab)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
#update
        self.update = QtWidgets.QPushButton(self.updatetab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.update.sizePolicy().hasHeightForWidth())
        self.update.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(133, 133, 133))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.update.setPalette(palette)
        self.update.setStyleSheet("border-image: url(:/theme/circuit.jpg);\n"
"font: 75 italic 16pt \"URW Bookman L\";")
        self.update.setObjectName("update")
        self.gridLayout_3.addWidget(self.update, 0, 0, 1, 1)
        self.update.clicked.connect(update)

#END UPDATE TAB
        self.tabWidget.addTab(self.updatetab, "")
#START INSTALL TAB
        self.installtab = QtWidgets.QWidget()
        self.installtab.setObjectName("installtab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.installtab)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
#install all no extras
        self.installnoextras = QtWidgets.QPushButton(self.installtab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.installnoextras.sizePolicy().hasHeightForWidth())
        self.installnoextras.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(133, 133, 133))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.installnoextras.setPalette(palette)
        self.installnoextras.setStyleSheet("border-image: url(:/theme/circuit.jpg);\n"
"font: 75 italic 16pt \"URW Bookman L\";")
        self.installnoextras.setObjectName("installnoextras")
        self.gridLayout_2.addWidget(self.installnoextras, 0, 1, 1, 1)
        self.installnoextras.clicked.connect(installnoextras)
#install
        self.install = QtWidgets.QPushButton(self.installtab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.install.sizePolicy().hasHeightForWidth())
        self.install.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(133, 133, 133))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.install.setPalette(palette)
        self.install.setStyleSheet("border-image: url(:/theme/circuit.jpg);\n"
"font: 75 italic 16pt \"URW Bookman L\";")
        self.install.setObjectName("install")
        self.gridLayout_2.addWidget(self.install, 0, 0, 1, 1)
        self.install.clicked.connect(install)
#install all
        self.installall = QtWidgets.QPushButton(self.installtab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.installall.sizePolicy().hasHeightForWidth())
        self.installall.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(133, 133, 133))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.installall.setPalette(palette)
        self.installall.setStyleSheet("border-image: url(:/theme/circuit.jpg);\n"
"font: 75 italic 16pt \"URW Bookman L\";")
        self.installall.setObjectName("installall")
        self.gridLayout_2.addWidget(self.installall, 1, 0, 1, 2)
        self.installall.clicked.connect(installall)
#END INSTALL TAB
        self.tabWidget.addTab(self.installtab, "")
#START UNINSTALL TAB
        self.uninstalltab = QtWidgets.QWidget()
        self.uninstalltab.setObjectName("uninstalltab")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.uninstalltab)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
#uninstall
        self.uninstall = QtWidgets.QPushButton(self.uninstalltab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uninstall.sizePolicy().hasHeightForWidth())
        self.uninstall.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(133, 133, 133))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.uninstall.setPalette(palette)
        self.uninstall.setStyleSheet("border-image: url(:/theme/circuit.jpg);\n"
"font: 75 italic 16pt \"URW Bookman L\";")
        self.uninstall.setObjectName("uninstall")
        self.gridLayout_4.addWidget(self.uninstall, 0, 0, 1, 1)
        self.uninstall.clicked.connect(uninstall)
#uninstall extras
        self.uninstallextras = QtWidgets.QPushButton(self.uninstalltab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uninstallextras.sizePolicy().hasHeightForWidth())
        self.uninstallextras.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(133, 133, 133))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.uninstallextras.setPalette(palette)
        self.uninstallextras.setStyleSheet("border-image: url(:/theme/circuit.jpg);\n"
"font: 75 italic 16pt \"URW Bookman L\";")
        self.uninstallextras.setObjectName("uninstallextras")
        self.gridLayout_4.addWidget(self.uninstallextras, 0, 1, 1, 1)
        self.uninstallextras.clicked.connect(uninstallextras)

        self.tabWidget.addTab(self.uninstalltab, "")
        self.gridLayout.addWidget(self.tabWidget, 1, 0, 1, 1)
        PlowInstallerWindow.setCentralWidget(self.centralwidget)
#END UNINSTALL TAB
        self.retranslateUi(PlowInstallerWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(PlowInstallerWindow)

    def retranslateUi(self, PlowInstallerWindow):
        _translate = QtCore.QCoreApplication.translate
        PlowInstallerWindow.setWindowTitle(_translate("PlowInstallerWindow", "Plow Installer"))
        self.update.setText(_translate("PlowInstallerWindow", "Update The Plow"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.updatetab), _translate("PlowInstallerWindow", "Update"))
        self.installnoextras.setText(_translate("PlowInstallerWindow", "Install No Extras"))
        self.install.setText(_translate("PlowInstallerWindow", "Install The Plow"))
        self.installall.setText(_translate("PlowInstallerWindow", "Install All Clients"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.installtab), _translate("PlowInstallerWindow", "Install"))
        self.uninstall.setText(_translate("PlowInstallerWindow", "UnInstall"))
        self.uninstallextras.setText(_translate("PlowInstallerWindow", "UnInstall Extras"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.uninstalltab), _translate("PlowInstallerWindow", "UnInstall"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PlowInstallerWindow = QtWidgets.QMainWindow()
    ui = Ui_PlowInstallerWindow()
    ui.setupUi(PlowInstallerWindow)
    PlowInstallerWindow.show()
    sys.exit(app.exec_()) 
